### ISSUE TITLE
what kind of error is this? Is it because of python or what?

### ISSUE THREAD

**Issue by OMX2048** [andyp123/blender_vertex_color_master#49] opened 2024-06-10 09:41 UTC
![Desktop Screenshot 2024 06 10 - 16 32 10 34](https://github.com/andyp123/blender_vertex_color_master/assets/170619685/f82c2c34-98fb-4ab0-b8ca-d909478f2c9e)

**Comment by Andrej730** [comment] 2024-07-14 12:53
Duplicate of #42, resolved in the PR.

**Comment by andyp123** [comment] 2024-08-08 16:05
You may also want to try the [latest pre-release](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha). This should fix a lot more issues than just that.

**Closed by andyp123** 2024-08-08 16:05 UTC
